name: Release

on:
  pull_request:
    branches:
      - "main"
      - "alpha"
      - "beta"
    types:
      - opened
      - edited
      - synchronize
      - reopened
  push:
    branches:
      - "main"
      - "alpha"
      - "beta"
      - "feature/**"
      - "bug/**"
      - "docs/**"
      - "fix/**"
  workflow_dispatch:

permissions:
  id-token: write
  contents: write
  issues: write
  pull-requests: write

jobs:
  release:
    name: Release
    if: github.ref_protected == true && github.event_name == 'push'
    #needs: [build]
    runs-on: ubuntu-latest
    environment: release-test
    outputs:
      version: ${{ steps.semantic.outputs.release-version }}
      released: ${{ steps.semantic.outputs.new-release-published }}

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Fetch version from git history
        uses: docker://ghcr.io/codfish/semantic-release-action:v3
        id: semantic
        with:
          dry-run: true
          additional-packages: 'conventional-changelog-conventionalcommits@7'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
<<<<<<< HEAD

      - name: Create new semantic release
        uses: docker://ghcr.io/codfish/semantic-release-action:v3
        with:
          additional-packages: 'conventional-changelog-conventionalcommits@7'
          plugins: |
            [
              '@semantic-release/commit-analyzer',
              [
                "@semantic-release/release-notes-generator",
                {
                  "preset": "conventionalcommits",
                  "presetConfig": {
                    "types": [
                      { type: 'feat', section: 'Features', hidden: false },
                      { type: 'fix', section: 'Bug Fixes', hidden: false },
                      { type: 'perf', section: 'Performance Improvements', hidden: false },
                      { type: 'revert', section: 'Reverts', hidden: false },
                      { type: 'docs', section: 'Other Updates', hidden: false },
                      { type: 'style', section: 'Other Updates', hidden: false },
                      { type: 'chore', section: 'Other Updates', hidden: false },
                      { type: 'refactor', section: 'Other Updates', hidden: false },
                      { type: 'test', section: 'Other Updates', hidden: false },
                      { type: 'build', section: 'Other Updates', hidden: false },
                      { type: 'ci', section: 'Other Updates', hidden: false }
                    ]
                  }
                }
              ],
              '@semantic-release/github'
            ]
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
=======
>>>>>>> ccb2b9f (chore(config): adds automation)
