name: Release

on:
  pull_request:
    branches:
      - "main"
      - "alpha"
      - "beta"
    types:
      - opened
      - edited
      - synchronize
      - reopened
  push:
    branches:
      - "main"
      - "alpha"
      - "beta"
      - "feature/**"
      - "bug/**"
      - "docs/**"
      - "fix/**"
  workflow_dispatch:

permissions:
  id-token: write
  contents: write
  issues: write
  pull-requests: write

jobs:
  release:
    name: Release
    if: github.ref_protected == true && github.event_name == 'push'
    #needs: [build]
    runs-on: ubuntu-latest
    environment: release-test
    outputs:
      version: ${{ steps.semantic.outputs.release-version }}
      released: ${{ steps.semantic.outputs.new-release-published }}

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Fetch version from git history
        uses: docker://ghcr.io/codfish/semantic-release-action:v3
        id: semantic
        with:
          dry-run: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create new semantic release
        uses: docker://ghcr.io/codfish/semantic-release-action:v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
